1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [9]:
import numpy as np
x=np.random.randint(1,9,(3,3))
y=np.random.randint(1,9,(3,3))
 
print(x)
print(y)
 
z =np.dot(x,y)
print("\nDot product \n",z)
 
print("\nTranspose\n",np.transpose(z))

[[4 6 5]
 [1 3 6]
 [7 8 7]]
[[3 3 2]
 [8 8 4]
 [7 8 7]]

Dot product 
 [[ 95 100  67]
 [ 69  75  56]
 [134 141  95]]

Transpose
 [[ 95  69 134]
 [100  75 141]
 [ 67  56  95]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [10]:
import numpy as np
a=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(a)
det=np.linalg.det(a)
print(int(det))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
