1. Generate a 3 x 3 matrix using random module.

In [ ]:
import numpy as np
  
matrix = np.random.randint(10, size=(3, 3))
print(matrix)

[[3 6 3]
 [9 4 0]
 [6 1 0]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [13]:
import numpy as np
 
matrix_1 = np.random.randint(10,size=(4,4))
print(matrix_1)
 
matrix_2 = np.random.randint(10,size=(4,4))
print(matrix_2)
 
a = matrix_1.reshape(2,8)
b = matrix_2.reshape(2,8)
 
print(np.hstack((a,b)))
 
print(np.vstack((a,b)))

[[6 9 3 1]
 [3 4 7 4]
 [8 6 8 1]
 [9 4 7 4]]
[[7 1 8 9]
 [0 2 2 6]
 [5 4 8 3]
 [1 1 5 0]]
[[6 9 3 1 3 4 7 4 7 1 8 9 0 2 2 6]
 [8 6 8 1 9 4 7 4 5 4 8 3 1 1 5 0]]
[[6 9 3 1 3 4 7 4]
 [8 6 8 1 9 4 7 4]
 [7 1 8 9 0 2 2 6]
 [5 4 8 3 1 1 5 0]]
