1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [3]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
 
sum = np.sum(mat)
print("\n Sum is : ",sum)


 The Matrix is:
 [[4 6 1]
 [5 4 4]
 [4 0 0]]

 Sum is :  28


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [5]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
 
col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col)
 
row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)


 The Matrix is:
 [[7 6 4]
 [3 0 4]
 [6 5 0]]

 Sum of Columns:
 [16 11  8]

 Sum of Columns:
 [17  7 11]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [6]:
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat)
 
min = np.min(mat)
print("\n Minimum Value is\n",min)
 
max = np.max(mat)
print("\n Maximum Value is\n",max)
 
mean = np.mean(mat)
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[14  9  0  1]
 [ 5 10  4 13]
 [ 0  4  1 10]
 [ 5 14  6  9]]

 Minimum Value is
 0

 Maximum Value is
 14

 Minimum Value is
 6.5625


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [7]:
import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat)
 
print("\nThe 7th row is :\n",mat[7,:])
 
print("\nThe 4-8th row is :\n",mat[4:8,:])
 
print("\nThe value at (5,5) is :\n",mat[5,5])
 
print("\nThe 5th column) is :\n",mat[:,5])
 
print("\nThe 2-5th column) is :\n",mat[:,2:5])


 The Matrix is:
 [[59 94 67 37 90 73 97 61 80 63]
 [92 54 49 62 87 40 73 25 91 88]
 [41 14 73 30 82 18 72 33 17 95]
 [53 50 72 79 82 29 15 12 81  4]
 [82  1 64 27 13 67  8 97 85 57]
 [ 7 78 66 36 17 64 28 37 81 90]
 [93 27 28 50 52 27 30 80 30 30]
 [28 21 22 27 14 10 44 19 29 72]
 [90  5 34 26 52 17 18 20 93 78]
 [67 40  2 24 76 90 75 49 53 12]]

The 7th row is :
 [28 21 22 27 14 10 44 19 29 72]

The 4-8th row is :
 [[82  1 64 27 13 67  8 97 85 57]
 [ 7 78 66 36 17 64 28 37 81 90]
 [93 27 28 50 52 27 30 80 30 30]
 [28 21 22 27 14 10 44 19 29 72]]

The value at (5,5) is :
 64

The 5th column) is :
 [73 40 18 29 67 64 27 10 17 90]

The 2-5th column) is :
 [[67 37 90]
 [49 62 87]
 [73 30 82]
 [72 79 82]
 [64 27 13]
 [66 36 17]
 [28 50 52]
 [22 27 14]
 [34 26 52]
 [ 2 24 76]]
