1. Generate a 3 x 3 matrix using random module.

In [2]:
import numpy as np
  
matrix = np.random.randint(10, size=(3, 3))
print(matrix)

[[3 6 3]
 [9 4 0]
 [6 1 0]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [5]:
import numpy as np
 
matrix = np.random.randint(10,size=(4,4))
print(matrix)
 
newmatrix = matrix.reshape(2,8)
print("The Reshaped Matrix is \n",newmatrix)
v_stack = np.vstack(newmatrix)
print("Vertically Stacked Matrix is \n",vstack)
h_stack = np.hstack(newmatrix)
print("Horizontally Stacked Matrix is \n",hstack)

[[5 1 2 9]
 [1 3 9 4]
 [8 8 1 0]
 [4 5 8 7]]
The Reshaped Matrix is 
 [[5 1 2 9 1 3 9 4]
 [8 8 1 0 4 5 8 7]]
Vertically Stacked Matrix is 
 [[2 8 6 4 5 9 8 6]
 [0 3 0 5 5 8 7 9]]
Horizontally Stacked Matrix is 
 [2 8 6 4 5 9 8 6 0 3 0 5 5 8 7 9]
